name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install base
        run: |
          npm install --legacy-peer-deps

      - name: install layer
        working-directory: common-layer/nodejs
        run: |
          npm install --legacy-peer-deps

      - name: build lambdas
        run: |
          node esbuild-lambda.js 

      - name: build front
        run: |
          npx webpack         
