name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install base
        run: |
          npm ci --include=dev --legacy-peer-deps

      - name: install layer
        working-directory: common-layer/nodejs
        run: |
          npm ci --include=dev --legacy-peer-deps

      - name: build lambdas
        run: |
          node esbuild-lambda.js 

      - name: build front
        run: |
          npx webpack      

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_aws_account', env.branch_name)]}}:role/github-role
          role-session-name: terraform-session
          aws-region: eu-west-2

      - name: terraform init
        working-directory: terraform
        run: |
          terraform init