name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload Webpack Bundle
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install base
        run: |
          npm install

      - name: install layer
        workdir: common-layer/nodejs
        run: |
          npm install
